package com.joseneto.englishverse.model.enums;

public enum XpEventType {
    PRESENTATION_COMPLETED,
    PRACTICE_COMPLETED,
    PRODUCTION_SUBMITTED,
    ACTIVITY_REPEATED,
    PRACTICE_STAGE_COMPLETED,
    MODULE_COMPLETED,
    TOPIC_COMPLETED,
    DAILY_ACTIVITY_BONUS,
    STAR_CAPSULE_OPENED
}
